---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/digitalw/public_html
    - export REPO_BUILD_PATH=/home/digitalw/repositories/digital-web-art/frontend/dist
    - /bin/rm -rf $DEPLOY_PATH/assets
    - /bin/cp -r $REPO_BUILD_PATH/assets* $DEPLOY_PATH/assets
