networks:
  app-network:
    name: app-network
    driver: bridge

services:
  web:
    container_name: web
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
    - PORT
    - VITE_PORT
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network